### ISSUE TITLE
Incorrect link for supported platforms?

### ISSUE THREAD

**Issue by mphilipps** [Icinga/packages.icinga.com#10]
hi,
The link in the README.html/.md points to https://www.icinga.com/support/ , which contains information regarding support subscriptions and not about supported platforms.

**Comment by mphilipps** [comment]
Sorry, my bad. It felt like the page was over after the request a quote form.

**Comment by dnsmichi** [comment]
We needed to find a central place to manage this, for both community and partner customers. I agree that is not optimal, but a first step. Thanks for your feedback :)
