### ISSUE TITLE
/IcingaForWindows: required command `Install-Module icinga-powershell-framework` not obvious

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/packages.icinga.com#23]

**Comment by LordHepipud** [comment]
Hello

do you have any more details on this? Isn't the documentation linked to Icinga for Windows?
Could you please add some details what you would expect?

**Comment by Al2Klimov** [comment]
## Status quo

The command shown on https://packages.icinga.com/IcingaForWindows/ doesn’t work:

```ps1
Add-IcingaRepository `
    -Name 'Icinga Stable' `
    -RemotePath 'https://packages.icinga.com/IcingaForWindows/stable/ifw.repo.json';
```

... even with `Install-Module icinga-powershell-framework`, even if done in another PS window.

## I'd like you to

choose between the following and open a PR here. (Edit https://github.com/Icinga/packages.icinga.com/blob/master/IcingaForWindows/README.html)

* Don’t show any commands, users have to RTFlinkedM
* Show all commands required by the shown commands

**Comment by LordHepipud** [comment]
Please have a look on the linked PR. I would prefer to neither remove the commands nor to add all installation commands.

Instead, I think it would be a better option to more clearly tell users to follow the installation guide before running the commands.
