### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by jenslink** [Icinga/packages.icinga.com#9]
Hi,

so we have 2018 and packages.icinga.com still does not have IPv6.  

I asked before (01. December 2015) and got the answer that IPv6 support is planned for mid 2016. That was two years ago.

Jens

**Comment by dnsmichi** [comment]
Very deconstructive issue, I really dislike your tone.

Btw, this already is open here: Icinga/icinga-packaging#93
Closing therefore.
